### ISSUE TITLE
Copper layers at the edges of PCB cause short-circuit

### ISSUE THREAD

**Issue by kasraghu** [openvlc/OpenVLC#3]
The copper is poured until the edge of PCB on Top and Bottom layers. This caused a short-circuit on the edge. There should be a gap between copper pour and mechanical edge of PCB.

**Comment by salehpaz** [comment]
I also noticed smoke and fire between the layers of the board. at the redpoint.

![VLC1_3](https://user-images.githubusercontent.com/62707144/109122980-9faa7b00-7749-11eb-828f-6f5c21759b65.jpeg)

**Comment by borja-genoves** [comment]
Dear kasraghu and salehpaz,

First of all, I would like to apologize for such error. We didn't notice this before. With proper PCB manufacturing top and bottom layers don’t short even if copper is poured until the edge. To be on safe side, as kasraghu correctly mentioned, this can be easily solved by adding isolation of 1-2 mm on the edges.

We are working on it.
Thanks a lot and best regards,
Borja.

**Comment by borja-genoves** [comment]
This was addressed and uploaded. Thanks for your suggestion. I am closing the issue.
